// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use a placeholder when QANDA_DATABASE_URL is unset so `prisma generate` can run
// (e.g. during Vercel install). Migrate and runtime always use the real env var.
const databaseUrl =
  process.env.QANDA_DATABASE_URL || "postgresql://localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
